[package]
cairo-version = "=2.10.1"
name = "crimson_fate"
version = "1.5.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate"                      # scarb run migrate

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.6.0-alpha.2" }
cartridge_vrf = { git = "https://github.com/cartridge-gg/vrf.git"}

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]
sierra = true
casm = true

[dev-dependencies]
cairo_test = "=2.10.1"
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.6.0-alpha.2" }

[profile.mainnet]